# Generated by Django 3.1.7 on 2021-03-26 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0015_auto_20210325_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='items',
            new_name='item',
        ),
    ]
