# Generated by Django 3.1.7 on 2021-04-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0017_auto_20210404_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
